[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atb"
version = "0.1"
description = "free use library for interaction with telegram api via http"
authors = [
    { name = "Dark Mathery" }
]
dependencies = [
    "aiohttp",
]
